version: 0.0
os: linux
files:
  - source: /webapp
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 755

hooks:
  - BeforeInstall:
      - location: scripts/before_install.sh
        timeout: 300
        runas: root

  - AfterInstall:
      - location: scripts/after_install.sh
        timeout: 600
        runas: root

  - ApplicationStart:
      - location: scripts/application_start.sh
        timeout: 60
        runas: root

  - ApplicationStop:
      - location: scripts/application_stop.sh
        timeout: 30
        runas: root

  - ValidateService:
      - location: scripts/validate_service.sh
        timeout: 30
        runas: root

  - BeforeBlockTraffic:
      - location: scripts/before_block_traffic.sh
        timeout: 30
        runas: root

  - BlockTraffic:
      - location: scripts/block_traffic.sh
        timeout: 30
        runas: root

  - AfterBlockTraffic:
      - location: scripts/after_block_traffic.sh
        timeout: 30
        runas: root

  - BeforeAllowTraffic:
      - location: scripts/before_allow_traffic.sh
        timeout: 30
        runas: root

  - AllowTraffic:
      - location: scripts/allow_traffic.sh
        timeout: 30
        runas: root

  - AfterAllowTraffic:
      - location: scripts/after_allow_traffic.sh
        timeout: 30
        runas: root